apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  finalizers:
  - finalizers.fluxcd.io
  generation: 4
  name: nkp-gitops-poc
  namespace: waystar-poc-w4xpl-4thwm
spec:
  interval: 3m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/WaystarInc/nkp-gitops-poc
  