apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    caren.nutanix.com/cluster-uuid: 0198388a-36b6-71c7-9318-905d068d1898
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: nkp-flux
    konvoy.d2iq.io/provider: nutanix
  name: nkp-flux
  namespace: waystar-poc-w4xpl-4thwm
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: ""
    port: 0
  topology:
    class: nkp-nutanix-v2.14.1
    controlPlane:
      metadata: {}
      replicas: 3
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: nkp-flux-pc-credentials
            strategy: HelmAddon
          clusterAutoscaler:
            strategy: HelmAddon
          cni:
            provider: Cilium
            strategy: HelmAddon
          cosi:
            strategy: HelmAddon
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: nkp-flux-pc-credentials-for-csi
                storageClassConfigs:
                  volume:
                    allowExpansion: true
                    parameters:
                      csi.storage.k8s.io/fstype: ext4
                      description: CSI StorageClass nutanix-volume for nkp-flux
                      flashMode: DISABLED
                      hypervisorAttached: ENABLED
                      storageContainer: default
                      storageType: NutanixVolumes
                    reclaimPolicy: Delete
                    volumeBindingMode: WaitForFirstConsumer
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd:
            strategy: HelmAddon
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - end: 10.38.238.19
                start: 10.38.238.18
            provider: MetalLB
        controlPlane:
          nutanix:
            machineDetails:
              bootType: uefi
              cluster:
                name: PHX-POC238
                type: name
              image:
                name: nkp-rocky-9.5-release-1.31.9-20250702204537.qcow2
                type: name
              memorySize: 16Gi
              subnets:
              - name: primary-PHX-POC238
                type: name
              systemDiskSize: 80Gi
              vcpuSockets: 4
              vcpusPerSocket: 1
        dns:
          coreDNS: {}
        encryptionAtRest:
          providers:
          - secretbox: {}
        globalImageRegistryMirror:
          url: http://registry.nutanixdemo.com/docker.io
        nutanix:
          controlPlaneEndpoint:
            host: 10.38.238.17
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: nkp-flux-pc-credentials
            insecure: true
            url: https://10.38.238.7:9440
    version: v1.31.9
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "4"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "4"
        name: md-0
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  cluster:
                    name: PHX-POC238
                    type: name
                  image:
                    name: nkp-rocky-9.5-release-1.31.9-20250702204537.qcow2
                    type: name
                  memorySize: 32Gi
                  subnets:
                  - name: primary-PHX-POC238
                    type: name
                  systemDiskSize: 80Gi
                  vcpuSockets: 8
                  vcpusPerSocket: 1
---
apiVersion: v1
data:
  credentials: WwogICAgewogICAgICAgICJ0eXBlIjogImJhc2ljX2F1dGgiLAogICAgICAgICJkYXRhIjogewogICAgICAgICAgICAicHJpc21DZW50cmFsIjogewogICAgICAgICAgICAgICAgInVzZXJuYW1lIjogImFkbWluIiwKICAgICAgICAgICAgICAgICJwYXNzd29yZCI6ICJueDJUZWNoNDMyISIKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KXQ==
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: nkp-flux
    konvoy.d2iq.io/provider: nutanix
  name: nkp-flux-pc-credentials
  namespace: waystar-poc-w4xpl-4thwm
type: Opaque
---
apiVersion: v1
data:
  key: MTAuMzguMjM4Ljc6OTQ0MDphZG1pbjpueDJUZWNoNDMyIQ==
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: nkp-flux
    konvoy.d2iq.io/provider: nutanix
  name: nkp-flux-pc-credentials-for-csi
  namespace: waystar-poc-w4xpl-4thwm
type: Opaque
